import { Card } from '../Card'
export const cards: Card[] = [
  {
    id: 1,
    header: 'Javascript',
    subheader: 'The language of the web',
    avatar: 'avatar.png',
    title: 'Developer',
    name: 'Liam Neville',
    link: 'https://liamneville.me',
    tags: ['HTML', 'CSS', 'JavaScript', 'React'],
  },
  {
    id: 2,
    header: 'Rust',
    subheader: 'Safe, fast and friendly systems language',
    avatar: 'avatar.png',
    title: 'Developer',
    name: 'Liam Neville',
    link: 'https://liamneville.me',
    tags: ['Systems', 'Mozilla', 'Rust'],
  },
  {
    id: 3,
    header: 'Java',
    subheader:
      'The popular, verbose and modular backend language of the industry',
    avatar: 'avatar.png',
    title: 'Developer',
    name: 'Liam Neville',
    link: 'https://liamneville.me',
    tags: ['Spring', 'Maven', 'TomCat'],
  },
  {
    id: 4,
    header: 'Scheme',
    subheader: 'Functional, easy-to-learn academic language',
    avatar: 'avatar.png',
    title: 'Developer',
    name: 'Liam Neville',
    link: 'https://liamneville.me',
    tags: ['Racket', 'Scheme', 'Functional'],
  },
  {
    id: 5,
    header: 'Python',
    subheader:
      'The simple scripting language that dominates ML, AI and data science',
    avatar: 'avatar.png',
    title: 'Developer',
    name: 'Liam Neville',
    link: 'https://liamneville.me',
    tags: ['Python', 'ML', 'AI'],
  },
  {
    id: 6,
    header: 'TypeScript',
    subheader:
      "JavaScript with Types and much more. Don't do web-dev on hard-mode.",
    avatar: 'avatar.png',
    title: 'Developer',
    name: 'Liam Neville',
    link: 'https://liamneville.me',
    tags: ['TypeScript', 'JavaScript'],
  },
  {
    id: 7,
    header: 'Ruby',
    subheader:
      'Object orientation to the extreme! Super high level and easy to read',
    avatar: 'avatar.png',
    title: 'Developer',
    name: 'Liam Neville',
    link: 'https://liamneville.me',
    tags: ['Ruby', 'Rails'],
  },
  {
    id: 8,
    header: 'C#',
    subheader: "Build production apps fast with Microsoft's great tooling",
    avatar: 'avatar.png',
    title: 'Developer',
    name: 'Liam Neville',
    link: 'https://liamneville.me',
    tags: ['.NET Core', 'WinForms', 'C#'],
  },
]
